# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_mzmat_eic_cpp <- function(intensity_values, mz_values, scanindex_values, scantime_values, mz_range) {
    .Call(`_cppFuncs_get_mzmat_eic_cpp`, intensity_values, mz_values, scanindex_values, scantime_values, mz_range)
}

get_rois_cpp <- function(ints, min_width, missing_scans = 1L) {
    .Call(`_cppFuncs_get_rois_cpp`, ints, min_width, missing_scans)
}

overlap_rois_cpp <- function(rois) {
    .Call(`_cppFuncs_overlap_rois_cpp`, rois)
}

descend_min_cpp <- function(y, center, minPts = 1L) {
    .Call(`_cppFuncs_descend_min_cpp`, y, center, minPts)
}

narrow_rt_boundaries_extend_cpp <- function(xrange, center, y, minPts = 1L) {
    .Call(`_cppFuncs_narrow_rt_boundaries_extend_cpp`, xrange, center, y, minPts)
}

narrow_rt_boundaries_reduce_cpp <- function(xrange, center, y, minPts = 1L) {
    .Call(`_cppFuncs_narrow_rt_boundaries_reduce_cpp`, xrange, center, y, minPts)
}

ppm_to_da_vector <- function(mass, ppm) {
    .Call(`_cppFuncs_ppm_to_da_vector`, mass, ppm)
}

