# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ppm_to_da_vector <- function(mass, ppm) {
    .Call(`_cppFuncs_ppm_to_da_vector`, mass, ppm)
}

