#' @title Create user
#'
#' @description
#' create user entry in database
#'
#' @param db sqlite connection 
#' @param login string, user login to create
record_user <- function(db, login) {
	query <- sprintf("insert into user (user) values (\"%s\");", login)
	print(query)
	db_execute(db, query)
	last_user <<- login
	actualize$users <<- runif(1)
}

#' @title Create a project
#'
#' @description
#' create project entry in database
#'
#' @param db sqlite connection
#' @param name string, name of the project
#' @param comments string, comments about the project (not used yet)
record_project <- function(db, name, comments) {
	query <- sprintf("insert into project (name, comments, creation, modified) 
		values (\"%s\", \"%s\", Date(\"now\"), Date(\"now\"));", 
		name, comments)
	print(query)
	db_execute(db, query)
	last_project <<- db_get_query(db, "select last_insert_rowid();")[1, 1]
	actualize$projects <- runif(1)
}

#' @title Record sample
#'
#' @description
#' Record sample in database
#' Get various informations by calling function get_ms_file_infos()
#' create a blob object with a xcmsRaw object by xcms
#' if the size of blob is > 2Gb it records the ms file in the mzXML directory instead of the blob in database
#' 
#' @param db sqlite connection
#' @param project integer, project id
#' @param sample_name string, sample name
#' @param sample_id string, sample id
#' @param filepath string, path of the ms file
#' @param old_filepath string, path of the old file converted
#' @param polarity integer, can only be 0 (negative) or 1(positive)
#' @param ms_file OnDiskMSnExp, ms file object read by MSnbase pkg
#' @param thermo_file string, path to the file generated by thermoReader (only if file was a raw Thermo)
record_sample <- function(db, project, sample_name, sample_id, filepath, 
		old_filepath, polarity, ms_file, thermo_file = NULL) {
	print(paste('record', sample_name))
	
	polarity <- if(polarity == 0) "negative" else "positive"
	infos <- get_ms_file_infos(ms_file, thermo_file)
	print(infos)
	raw_data <- blob::blob(fst::compress_fst(serialize(
		xcms::xcmsRaw(filepath, mslevel = 1, profstep = 0), NULL), 
		compression = 100))
	print(raw_data)
	filepath <- if (length(raw_data[[1]]) >= 2 * 10**9) {
		print("file is too big for the database")
		print("recording mzXML instead")
		new_filepath <- file.path("mzXMLFiles", polarity, basename(filepath))
		file.copy(filepath, new_filepath)
		new_filepath
	} else ""
	
	query <- sprintf("insert into sample (sample, raw_data, raw_path, polarity, 
		path, instrument_model, instrument_manufacturer, software_name, 
		software_version, ion_source, analyzer, detector_type, resolution, 
		agc_target, maximum_it, number_of_scan_range, scan_range) values 
		(\"%s\", :a, \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", 
		\"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\");", 
		sample_name, old_filepath, polarity, filepath, 
		infos$instrument_model, infos$instrument_manufacturer, 
		infos$software_name, infos$software_version, infos$ion_source, 
		infos$analyzer, infos$detector_type, infos$resolution, infos$agc_target, 
		infos$maximum_it, infos$number_of_scan_range, infos$scan_range)
	print(query)
	db_execute(db, query, params = list(a = raw_data))
	rm(raw_data)
	gc()
	actualize$samples <- runif(1)
}

#' @title Record project_sample
#'
#' @description
#' associate a sample with a project in database
#'
#' @param db sqlite connection
#' @param project integer, project id
#' @param sample_name string, sample id
#' @param sample_id string, sample id
record_project_sample <- function(db, project, sample_name, sample_id) {
	query <- sprintf("insert into project_sample (project, sample, sample_id) 
		values (%s, \"%s\", \"%s\");", project, sample_name, sample_id)
	print(query)
	db_execute(db, query)
	actualize$project_samples <- runif(1)
}